# Kernel UAPI export (headers_install).
#
# Since phase 3 of the kernel/userland separation the exported headers are
# produced by the standalone ntclks checkout: this fragment delegates
# headers_install to it (passing the whitelist through), then publishes the
# result into $(O)/kernel-export/include for the userland, runtime and SDK
# builds. The whitelist in configs/header-export.list remains the single source
# of truth for what leaves the kernel's UAPI tree. Files are published through
# leonos-emit (content-change-only), so an unchanged export never retouches
# mtimes and never rebuilds userland objects; a header removed from the list is
# pruned from the export on the next install. tools/test_header_export.py
# enforces the exact set, self-contained compilation and the absence of private
# includes.

HEADER_EXPORT_LIST ?= $(LEONOS_SRC)/configs/header-export.list
HEADER_EXPORT_ROOT := $(O)/kernel-export
HEADER_EXPORT_INCLUDE := $(HEADER_EXPORT_ROOT)/include
HEADER_EXPORT_MANIFEST := $(HEADER_EXPORT_ROOT)/manifest.txt

HEADER_EXPORT_ENTRIES := $(shell sed -e 's/\#.*//' -e '/^[[:space:]]*$$/d' $(HEADER_EXPORT_LIST))

# The sub-build's own export tree; the checkout exports the same whitelist into
# its O before this side publishes it.
NTCLKS_EXPORT_INCLUDE := $(NTCLKS_O)/kernel-export/include

# Delegation + publish. The recipe runs on every invocation (FORCE): the
# checkout decides internally whether anything changed, and the publish below is
# content-stable, so a no-op check writes nothing and moves no mtime. The
# sub-make line is a single command after its guard so the shell execs it (it
# dies with this make on an interrupt), and the guard keeps `make -n` silent:
# recipe lines containing $(MAKE) run even under -n.
$(HEADER_EXPORT_MANIFEST): FORCE $(LEONOS_EMIT)
	+$(Q)case "$${MAKEFLAGS%% *}" in *n*) exit 0 ;; esac; \
	if [ ! -f '$(NTCLKS_DIR)/Makefile' ]; then \
	    printf '%s\n' \
	        'ntclks adapter: kernel checkout not found: $(NTCLKS_DIR)/Makefile' \
	        '' \
	        'The exported headers come from the standalone ntclks checkout' \
	        '(kernel/userland separation phase 3). Mount or initialize the' \
	        'checkout at NTCLKS_DIR (default: $(LEONOS_SRC)/kernel/ntclks, the' \
	        'tracked kernel sources until phase 5), or point NTCLKS_DIR at an' \
	        'existing checkout, e.g. NTCLKS_DIR=/path/to/ntclks or NTCLKS_DIR=.' >&2; \
	    exit 1; \
	fi; \
	exec $(MAKE) -C '$(NTCLKS_DIR)' O='$(NTCLKS_O)' ARCH='$(ARCH)' \
	    PROFILE='$(PROFILE)' SOURCE_DATE_EPOCH='$(SOURCE_DATE_EPOCH)' \
	    headers_install HEADER_EXPORT_LIST='$(HEADER_EXPORT_LIST)'
	$(Q)set -eu; \
	mkdir -p '$(HEADER_EXPORT_INCLUDE)'; \
	for entry in $(HEADER_EXPORT_ENTRIES); do \
	    case "$$entry" in \
	    include/uapi/*) rel=$${entry#include/uapi/} ;; \
	    *) echo "headers_install: $$entry: not under include/uapi/" >&2; exit 1 ;; \
	    esac; \
	    test -f "$(NTCLKS_EXPORT_INCLUDE)/$$rel" || { \
	        echo "headers_install: $$entry: not exported by $(NTCLKS_DIR)" >&2; \
	        exit 1; }; \
	    mkdir -p "$(HEADER_EXPORT_INCLUDE)/$$(dirname "$$rel")"; \
	    $(LEONOS_EMIT) --input "$(NTCLKS_EXPORT_INCLUDE)/$$rel" \
	        --output "$(HEADER_EXPORT_INCLUDE)/$$rel"; \
	done; \
	{ printf '%s\n' '# generated by headers_install; source: configs/header-export.list'; \
	  for entry in $(HEADER_EXPORT_ENTRIES); do printf '%s\n' "$${entry#include/uapi/}"; done; \
	} | LC_ALL=C sort > '$(HEADER_EXPORT_MANIFEST).tmp'; \
	$(LEONOS_EMIT) --input '$(HEADER_EXPORT_MANIFEST).tmp' --output '$(HEADER_EXPORT_MANIFEST)'; \
	rm -f '$(HEADER_EXPORT_MANIFEST).tmp'; \
	find '$(HEADER_EXPORT_INCLUDE)' -type f -printf '%P\n' | LC_ALL=C sort > '$(HEADER_EXPORT_ROOT)/present.tmp'; \
	sed -e '/^#/d' -e '/^[[:space:]]*$$/d' '$(HEADER_EXPORT_MANIFEST)' | LC_ALL=C sort > '$(HEADER_EXPORT_ROOT)/want.tmp'; \
	comm -23 '$(HEADER_EXPORT_ROOT)/present.tmp' '$(HEADER_EXPORT_ROOT)/want.tmp' \
	  | (cd '$(HEADER_EXPORT_INCLUDE)' && xargs -r rm -f); \
	rm -f '$(HEADER_EXPORT_ROOT)/present.tmp' '$(HEADER_EXPORT_ROOT)/want.tmp'; \
	find '$(HEADER_EXPORT_INCLUDE)' -mindepth 1 -type d -empty -delete

.PHONY: headers_install
headers_install: $(HEADER_EXPORT_MANIFEST)
