/* Convert litehtml's pinned GB18030 index into the LeonOS GBK lookup tables. */
#define _POSIX_C_SOURCE 200809L
#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tools/host/common/io.h"

#define POINTER_COUNT 23940u
struct entry { uint32_t unicode; uint16_t pointer; };

static int compare_entries(const void *left, const void *right)
{
    const struct entry *a = left, *b = right;
    if (a->unicode != b->unicode) return a->unicode < b->unicode ? -1 : 1;
    return (a->pointer > b->pointer) - (a->pointer < b->pointer);
}

static int parse_table(char *text, uint32_t *values)
{
    char *p = strstr(text, "gb18030_decoder::m_index[]");
    if (!p) return -1;
    p += strlen("gb18030_decoder::m_index[]");
    while (isspace((unsigned char)*p)) ++p;
    if (*p++ != '=') return -1;
    while (isspace((unsigned char)*p)) ++p;
    if (*p++ != '{') return -1;
    size_t count = 0;
    for (;;) {
        while (isspace((unsigned char)*p)) ++p;
        if (*p == '}') break;
        uint32_t value;
        if (!strncmp(p, "null", 4)) { value = 0; p += 4; }
        else {
            if (!isdigit((unsigned char)*p)) return -1;
            errno = 0;
            char *end;
            unsigned long parsed = strtoul(p, &end, 10);
            if (errno || parsed > 0x10ffffUL) return -1;
            value = (uint32_t)parsed;
            p = end;
        }
        if (count < POINTER_COUNT) values[count] = value;
        ++count;
        while (isspace((unsigned char)*p)) ++p;
        if (*p == ',') ++p;
        else if (*p != '}') return -1;
    }
    return count >= POINTER_COUNT ? 0 : -1;
}

static int render(FILE *out, const uint32_t *values)
{
    struct entry sorted[POINTER_COUNT];
    size_t count = 0;
    for (unsigned i = 0; i < POINTER_COUNT; ++i)
        if (values[i]) sorted[count++] = (struct entry){values[i], (uint16_t)i};
    qsort(sorted, count, sizeof(*sorted), compare_entries);
    fprintf(out, "/* Generated by leonos-gbk. Do not edit. */\n"
        "#ifndef LEONOS_GENERATED_GBK_TABLE_H\n#define LEONOS_GENERATED_GBK_TABLE_H\n"
        "#include <stdint.h>\n#define LEONOS_GBK_POINTER_COUNT %uu\n"
        "#define LEONOS_GBK_MAPPED_COUNT %zuu\n"
        "static const uint32_t leonos_gbk_to_unicode[LEONOS_GBK_POINTER_COUNT] = {\n",
        POINTER_COUNT, count);
    for (unsigned i = 0; i < POINTER_COUNT; ++i)
        fprintf(out, "%uu,%s", values[i], i % 12 == 11 ? "\n" : " ");
    fputs("\n};\nstatic const uint16_t leonos_gbk_unicode_pointers[LEONOS_GBK_MAPPED_COUNT] = {\n", out);
    for (size_t i = 0; i < count; ++i)
        fprintf(out, "%uu,%s", (unsigned)sorted[i].pointer, i % 16 == 15 ? "\n" : " ");
    fputs("\n};\n#endif\n", out);
    return ferror(out) ? -1 : 0;
}

int main(int argc, char **argv)
{
    if (argc == 2 && !strcmp(argv[1], "--help")) {
        puts("usage: leonos-gbk SOURCE OUTPUT"); return 0;
    }
    if (argc != 3) { fputs("usage: leonos-gbk SOURCE OUTPUT\n", stderr); return 2; }
    struct byte_buffer source = {0};
    uint32_t values[POINTER_COUNT];
    char *rendered = NULL;
    size_t length = 0;
    int result = 1;
    if (read_file_all(argv[1], &source) < 0 ||
        buffer_reserve(&source, source.len + 1) < 0) goto done;
    source.data[source.len] = 0;
    if (memchr(source.data, 0, source.len) || parse_table((char *)source.data, values)) {
        fprintf(stderr, "leonos-gbk: invalid or incomplete GB18030 index in %s\n", argv[1]);
        goto done;
    }
    FILE *out = open_memstream(&rendered, &length);
    if (!out) goto done;
    int failed = render(out, values);
    if (fclose(out)) failed = -1;
    if (failed || write_file_if_changed(argv[2], rendered, length, 0644)) goto done;
    result = 0;
done:
    if (result && errno) perror("leonos-gbk");
    free(rendered);
    buffer_destroy(&source);
    return result;
}
