#ifndef RELIEFOS_UAPI_FS_ABI_H
#define RELIEFOS_UAPI_FS_ABI_H

#include <stdint.h>
#include <linux/fcntl.h>

#define RELIEFOS_FS_NAME_LEN 128U
#define RELIEFOS_FS_PATH_LEN 256U
#define RELIEFOS_FS_MAX_ENTRIES 64U
#define RELIEFOS_FS_ACL_MAX_ACE 16U
#define RELIEFOS_FS_ACL_VERSION 1U
#define RELIEFOS_FS_TYPE_FILE 1U
#define RELIEFOS_FS_TYPE_DIR 2U
#define RELIEFOS_FS_TYPE_DEVICE 3U
#define RELIEFOS_FS_TYPE_SOCKET 4U
#define RELIEFOS_FS_TYPE_SYMLINK 5U
#define RELIEFOS_FS_TYPE_FIFO 6U
#define RELIEFOS_FS_ACL_PRINCIPAL_OWNER 1U
#define RELIEFOS_FS_ACL_PRINCIPAL_SYSTEM 2U
#define RELIEFOS_FS_ACL_PRINCIPAL_ADMINISTRATORS 3U
#define RELIEFOS_FS_ACL_PRINCIPAL_USERS 4U
#define RELIEFOS_FS_ACL_PRINCIPAL_EVERYONE 5U
#define RELIEFOS_FS_ACL_PRINCIPAL_GROUP 6U
#define RELIEFOS_FS_ACL_ACE_INHERITED 0x00000002U
#define RELIEFOS_FS_PERM_READ 0x00000001U
#define RELIEFOS_FS_PERM_WRITE 0x00000002U
#define RELIEFOS_FS_PERM_EXEC 0x00000004U
#define RELIEFOS_FS_PERM_DELETE 0x00000008U
#define RELIEFOS_FS_PERM_MANAGE 0x00000010U
#define RELIEFOS_FS_PERM_FULL (RELIEFOS_FS_PERM_READ | RELIEFOS_FS_PERM_WRITE | RELIEFOS_FS_PERM_EXEC | RELIEFOS_FS_PERM_DELETE | RELIEFOS_FS_PERM_MANAGE)
#define RELIEFOS_FS_ACL_FLAG_CORRUPT 0x00000001U
#define RELIEFOS_FS_ACL_FLAG_SYNTHETIC 0x00000002U
#define RELIEFOS_O_RDONLY LINUX_O_RDONLY
#define RELIEFOS_O_WRONLY LINUX_O_WRONLY
#define RELIEFOS_O_RDWR LINUX_O_RDWR
#define RELIEFOS_O_ACCMODE LINUX_O_ACCMODE
#define RELIEFOS_O_CREAT LINUX_O_CREAT
#define RELIEFOS_O_TRUNC LINUX_O_TRUNC
#define RELIEFOS_O_APPEND LINUX_O_APPEND
#define RELIEFOS_O_EXCL LINUX_O_EXCL
#define RELIEFOS_O_NONBLOCK LINUX_O_NONBLOCK
#define RELIEFOS_O_DIRECTORY LINUX_O_DIRECTORY
#define RELIEFOS_O_NOFOLLOW LINUX_O_NOFOLLOW
#define RELIEFOS_O_CLOEXEC LINUX_O_CLOEXEC
#define RELIEFOS_FS_IO_SLICE_BYTES 4096U
#define RELIEFOS_FS_FILE_WRITE_SLICE_BYTES (64U * 512U)
#define RELIEFOS_FS_READ_SLICE_BYTES (64U * 512U)
#define RELIEFOS_SEEK_SET 0
#define RELIEFOS_SEEK_CUR 1
#define RELIEFOS_SEEK_END 2

struct reliefos_stat { uint32_t type; uint32_t reserved; uint64_t size; };
struct reliefos_dir_entry { uint32_t type; char name[RELIEFOS_FS_NAME_LEN]; };
struct reliefos_dir_list { const char *path; uint32_t capacity; uint32_t count; struct reliefos_dir_entry *entries; };
struct reliefos_fs_acl_ace { uint32_t principal; uint32_t flags; uint32_t permissions; uint32_t reserved; };
struct reliefos_fs_acl { uint32_t version; uint32_t owner_uid; uint32_t flags; uint32_t ace_count; struct reliefos_fs_acl_ace aces[RELIEFOS_FS_ACL_MAX_ACE]; };

#endif
