/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/gpu_abi.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_UAPI_GPU_ABI_H
#define LEONOS_UAPI_GPU_ABI_H
#include <reliefos/gpu_abi.h>

/* Old names are macro aliases to the same declarations. */
#define LEONOS_GPU_ABI_VERSION RELIEFOS_GPU_ABI_VERSION
#define LEONOS_GPU_AVAILABLE RELIEFOS_GPU_AVAILABLE
#define LEONOS_GPU_BUSY_ESTIMATED RELIEFOS_GPU_BUSY_ESTIMATED
#define LEONOS_GPU_ERROR_COPYOUT RELIEFOS_GPU_ERROR_COPYOUT
#define LEONOS_GPU_ERROR_DRAW RELIEFOS_GPU_ERROR_DRAW
#define LEONOS_GPU_ERROR_FENCE RELIEFOS_GPU_ERROR_FENCE
#define LEONOS_GPU_ERROR_NONE RELIEFOS_GPU_ERROR_NONE
#define LEONOS_GPU_ERROR_PREPARE RELIEFOS_GPU_ERROR_PREPARE
#define LEONOS_GPU_ERROR_READBACK RELIEFOS_GPU_ERROR_READBACK
#define LEONOS_GPU_ERROR_REAP RELIEFOS_GPU_ERROR_REAP
#define LEONOS_GPU_ERROR_STATE RELIEFOS_GPU_ERROR_STATE
#define LEONOS_GPU_ERROR_UPLOAD RELIEFOS_GPU_ERROR_UPLOAD
#define LEONOS_GPU_FILL_LINE RELIEFOS_GPU_FILL_LINE
#define LEONOS_GPU_FILL_POINT RELIEFOS_GPU_FILL_POINT
#define LEONOS_GPU_FILL_SOLID RELIEFOS_GPU_FILL_SOLID
#define LEONOS_GPU_MAX_DRAWS RELIEFOS_GPU_MAX_DRAWS
#define LEONOS_GPU_MAX_HEIGHT RELIEFOS_GPU_MAX_HEIGHT
#define LEONOS_GPU_MAX_VERTICES RELIEFOS_GPU_MAX_VERTICES
#define LEONOS_GPU_MAX_WIDTH RELIEFOS_GPU_MAX_WIDTH
#define LEONOS_IOCTL_GPU_CREATE RELIEFOS_IOCTL_GPU_CREATE
#define LEONOS_IOCTL_GPU_DESTROY RELIEFOS_IOCTL_GPU_DESTROY
#define LEONOS_IOCTL_GPU_DIAGNOSTICS RELIEFOS_IOCTL_GPU_DIAGNOSTICS
#define LEONOS_IOCTL_GPU_INFO RELIEFOS_IOCTL_GPU_INFO
#define LEONOS_IOCTL_GPU_RENDER RELIEFOS_IOCTL_GPU_RENDER
#define leonos_gpu_context reliefos_gpu_context
#define leonos_gpu_destroy reliefos_gpu_destroy
#define leonos_gpu_diagnostics reliefos_gpu_diagnostics
#define leonos_gpu_draw reliefos_gpu_draw
#define leonos_gpu_frame reliefos_gpu_frame
#define leonos_gpu_info reliefos_gpu_info
#define leonos_gpu_vertex reliefos_gpu_vertex
#define leonos_gui_present_window reliefos_gui_present_window

#endif /* LEONOS_UAPI_GPU_ABI_H */
