/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/inputm_abi.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_UAPI_INPUTM_ABI_H
#define LEONOS_UAPI_INPUTM_ABI_H
#include <reliefos/inputm_abi.h>

/* Old names are macro aliases to the same declarations. */
#define LEONOS_INPUTM_ABBREV_LEN RELIEFOS_INPUTM_ABBREV_LEN
#define LEONOS_INPUTM_CONTEXT_FOCUSED RELIEFOS_INPUTM_CONTEXT_FOCUSED
#define LEONOS_INPUTM_CONTEXT_SECURE RELIEFOS_INPUTM_CONTEXT_SECURE
#define LEONOS_INPUTM_ID_LEN RELIEFOS_INPUTM_ID_LEN
#define LEONOS_INPUTM_MAX_CANDIDATES RELIEFOS_INPUTM_MAX_CANDIDATES
#define LEONOS_INPUTM_MAX_PROVIDERS RELIEFOS_INPUTM_MAX_PROVIDERS
#define LEONOS_INPUTM_NAME_LEN RELIEFOS_INPUTM_NAME_LEN
#define LEONOS_INPUTM_RENDER_CONTROLS RELIEFOS_INPUTM_RENDER_CONTROLS
#define LEONOS_INPUTM_RENDER_PIXELS RELIEFOS_INPUTM_RENDER_PIXELS
#define LEONOS_INPUTM_RESULT_CANCEL RELIEFOS_INPUTM_RESULT_CANCEL
#define LEONOS_INPUTM_RESULT_COMMIT RELIEFOS_INPUTM_RESULT_COMMIT
#define LEONOS_INPUTM_RESULT_COMPOSITION RELIEFOS_INPUTM_RESULT_COMPOSITION
#define LEONOS_INPUTM_RESULT_PASSTHROUGH RELIEFOS_INPUTM_RESULT_PASSTHROUGH
#define LEONOS_INPUTM_START_LOGIN RELIEFOS_INPUTM_START_LOGIN
#define LEONOS_INPUTM_START_MANUAL RELIEFOS_INPUTM_START_MANUAL
#define LEONOS_INPUTM_START_ON_DEMAND RELIEFOS_INPUTM_START_ON_DEMAND
#define LEONOS_INPUTM_TEXT_LEN RELIEFOS_INPUTM_TEXT_LEN
#define leonos_inputm_active_request reliefos_inputm_active_request
#define leonos_inputm_config_request reliefos_inputm_config_request
#define leonos_inputm_context reliefos_inputm_context
#define leonos_inputm_key_event reliefos_inputm_key_event
#define leonos_inputm_provider reliefos_inputm_provider
#define leonos_inputm_provider_list reliefos_inputm_provider_list
#define leonos_inputm_result reliefos_inputm_result
#define leonos_inputm_state reliefos_inputm_state

#endif /* LEONOS_UAPI_INPUTM_ABI_H */
