/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/system_abi.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_UAPI_SYSTEM_ABI_H
#define LEONOS_UAPI_SYSTEM_ABI_H
#include <reliefos/system_abi.h>

/* Old names are macro aliases to the same declarations. */
#define LEONOS_MACHINE_IDENTITY_FLAG_BOOT_DISK_GUID RELIEFOS_MACHINE_IDENTITY_FLAG_BOOT_DISK_GUID
#define LEONOS_MACHINE_IDENTITY_FLAG_BOOT_PARTITION_GUID RELIEFOS_MACHINE_IDENTITY_FLAG_BOOT_PARTITION_GUID
#define LEONOS_MACHINE_IDENTITY_FLAG_PLATFORM_UUID RELIEFOS_MACHINE_IDENTITY_FLAG_PLATFORM_UUID
#define LEONOS_MACHINE_IDENTITY_SOURCE_LEN RELIEFOS_MACHINE_IDENTITY_SOURCE_LEN
#define LEONOS_MACHINE_IDENTITY_UUID_LEN RELIEFOS_MACHINE_IDENTITY_UUID_LEN
#define LEONOS_MACHINE_IDENTITY_VENDOR_LEN RELIEFOS_MACHINE_IDENTITY_VENDOR_LEN
#define LEONOS_MACHINE_IDENTITY_VERSION RELIEFOS_MACHINE_IDENTITY_VERSION
#define LEONOS_NET_HOSTNAME_LEN RELIEFOS_NET_HOSTNAME_LEN
#define LEONOS_PERF_MAX_CPUS RELIEFOS_PERF_MAX_CPUS
#define LEONOS_SYSTEM_ARCH_LEN RELIEFOS_SYSTEM_ARCH_LEN
#define LEONOS_SYSTEM_COPYRIGHT_LEN RELIEFOS_SYSTEM_COPYRIGHT_LEN
#define LEONOS_SYSTEM_NAME_LEN RELIEFOS_SYSTEM_NAME_LEN
#define LEONOS_SYSTEM_TIME_LEN RELIEFOS_SYSTEM_TIME_LEN
#define LEONOS_SYSTEM_VERSION_LEN RELIEFOS_SYSTEM_VERSION_LEN
#define LEONOS_TASK_AFFINITY_GET RELIEFOS_TASK_AFFINITY_GET
#define LEONOS_TASK_AFFINITY_SET RELIEFOS_TASK_AFFINITY_SET
#define leonos_machine_identity reliefos_machine_identity
#define leonos_perf_cpu_info reliefos_perf_cpu_info
#define leonos_perf_info reliefos_perf_info
#define leonos_system_info reliefos_system_info
#define leonos_task_affinity reliefos_task_affinity
#define leonos_time_info reliefos_time_info
#define leonos_time_sync reliefos_time_sync

#endif /* LEONOS_UAPI_SYSTEM_ABI_H */
